name: Deploy to Dokku

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: vitalyliber/dokku-github-action@57b7fd8
      with:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: ssh.milanvit.net
        PROJECT: newcomers
        HOST_KEY: ssh.milanvit.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNHdWaoJW5vOZEMKNVlUsfP2MZmSY8A80hlXcjuzgYRHirjltU9aT1Z2mkTNZWKHmx3EknQipwD+DhQbzLhDgH1ypLuXIzXY8b89/fkLWXXgLS1rc39VaqwQpSZGJUkBx72ZfYFPMM3nqpNtJdggTLShArVX9zoLVjpD1ZkgmClCJ82pITOQr/26B6UlOha4aPLF3LkCssM8VF56JgOYP1xsOhmB/vel8vsCbNiqlnMH4pBg1NBuhrqMGO/NbimENpVEUTHVsNbcFsrQAmyKvKwOzO+lt8MT6UM+xt43s3ISR7HGtdeWyqG74kf3BNEcngnlN7hHFE7tRhuYqAIKqH
